before:
  hooks:
    - go mod download

archives:
  - id: temporal
    builds:
      - temporal
    name_template: "temporal_cli_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

  - id: temporal-doc-gen
    builds:
      - temporal-doc-gen
    name_template: "temporal_cli_doc_gen_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

builds:
  - id: temporal
    dir: cmd/temporal
    binary: temporal
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

  - id: temporal-doc-gen
    dir: cmd/docgen
    binary: temporal-doc-gen
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  skip: true

announce:
  skip: "true"
