before:
  hooks:
    - go mod download
    - go run ./cmd/docgen

archives:
  - id: temporal
    builds:
      - temporal
    name_template: "temporal_cli_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

  - id: temporal-doc-gen
    builds: []
    name_template: "temporal_cli_documentation_{{ .Version }}"
    wrap_in_directory: false
    files:
      - docs/*

builds:
  - id: temporal
    dir: cmd/temporal
    binary: temporal
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  skip: true

announce:
  skip: "true"
