package systemnexusgen_test

import (
	"go/parser"
	"go/token"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/temporalio/cli/internal/systemnexusgen"
)

func TestGenerateCode(t *testing.T) {
	ops := []systemnexusgen.Operation{
		{
			NexusPkgPath:   "go.temporal.io/api/workflowservice/v1/workflowservicenexus",
			NexusPkgName:   "workflowservicenexus",
			ServiceVarName: "TemporalAPIWorkflowserviceV1WorkflowService",
			OpFieldName:    "SignalWithStartWorkflowExecution",
			Request: systemnexusgen.ProtoType{
				PkgPath: "go.temporal.io/api/workflowservice/v1",
				PkgName: "workflowservice",
				Name:    "SignalWithStartWorkflowExecutionRequest",
			},
			Response: systemnexusgen.ProtoType{
				PkgPath: "go.temporal.io/api/workflowservice/v1",
				PkgName: "workflowservice",
				Name:    "SignalWithStartWorkflowExecutionResponse",
			},
		},
	}

	out, err := systemnexusgen.GenerateCode("temporalcli", ops)
	require.NoError(t, err)
	src := string(out)

	require.True(t, strings.HasPrefix(src, "// Code generated by gen-system-nexus. DO NOT EDIT."))
	require.Contains(t, src, "package temporalcli")
	require.Contains(t, src, "var systemNexusOps = map[systemNexusOpKey]systemNexusOpTypes{")
	require.Contains(t, src, "Operation: workflowservicenexus.TemporalAPIWorkflowserviceV1WorkflowService.SignalWithStartWorkflowExecution.Name(),")
	require.Contains(t, src, "func() proto.Message { return &workflowservice.SignalWithStartWorkflowExecutionRequest{} }")
	require.Contains(t, src, "func() proto.Message { return &workflowservice.SignalWithStartWorkflowExecutionResponse{} }")

	// Output must be valid, gofmt-able Go.
	_, err = parser.ParseFile(token.NewFileSet(), "gen.go", out, parser.AllErrors)
	require.NoError(t, err)
}
