package systemnexusgen

import (
	"bytes"
	"fmt"
	"go/format"
	"text/template"
)

// GenerateCode renders the systemNexusOps map for the given operations into a
// Go source file belonging to package pkgName.
func GenerateCode(pkgName string, ops []Operation) ([]byte, error) {
	im := newImportManager()
	protoAlias := im.add("google.golang.org/protobuf/proto", "proto")

	type entry struct {
		NexusAlias string
		ServiceVar string
		OpField    string
		ReqAlias   string
		ReqName    string
		RespAlias  string
		RespName   string
	}

	entries := make([]entry, 0, len(ops))
	for _, op := range ops {
		entries = append(entries, entry{
			NexusAlias: im.add(op.NexusPkgPath, op.NexusPkgName),
			ServiceVar: op.ServiceVarName,
			OpField:    op.OpFieldName,
			ReqAlias:   im.add(op.Request.PkgPath, op.Request.PkgName),
			ReqName:    op.Request.Name,
			RespAlias:  im.add(op.Response.PkgPath, op.Response.PkgName),
			RespName:   op.Response.Name,
		})
	}

	data := struct {
		Package    string
		ProtoAlias string
		Imports    []importEntry
		Entries    []entry
	}{
		Package:    pkgName,
		ProtoAlias: protoAlias,
		Imports:    im.entries(),
		Entries:    entries,
	}

	var buf bytes.Buffer
	if err := fileTemplate.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("rendering template: %w", err)
	}
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("formatting generated source: %w\n%s", err, buf.String())
	}
	return formatted, nil
}

var fileTemplate = template.Must(template.New("file").Parse(`// Code generated by gen-system-nexus. DO NOT EDIT.

package {{.Package}}

import (
{{- range .Imports}}
	{{if .Aliased}}{{.Alias}} {{end}}"{{.Path}}"
{{- end}}
)

// systemNexusOps is the generated registry of known system Nexus operations on
// the __temporal_system endpoint. Regenerate with 'make gen' after bumping the
// go.temporal.io/api dependency.
var systemNexusOps = map[systemNexusOpKey]systemNexusOpTypes{
{{- range .Entries}}
	{
		Endpoint:  temporalSystemNexusEndpoint,
		Operation: {{.NexusAlias}}.{{.ServiceVar}}.{{.OpField}}.Name(),
	}: {
		NewRequest:  func() {{$.ProtoAlias}}.Message { return &{{.ReqAlias}}.{{.ReqName}}{} },
		NewResponse: func() {{$.ProtoAlias}}.Message { return &{{.RespAlias}}.{{.RespName}}{} },
	},
{{- end}}
}
`))

// importEntry is a single import line in the generated file.
type importEntry struct {
	Path    string
	Alias   string
	Aliased bool // true when Alias differs from the package's natural name
}

// importManager assigns collision-free aliases to imported packages, preferring
// each package's natural name.
type importManager struct {
	byPath map[string]*importEntry
	used   map[string]bool
	order  []string
}

func newImportManager() *importManager {
	return &importManager{byPath: map[string]*importEntry{}, used: map[string]bool{}}
}

// add registers a package path with its natural name and returns the alias to
// use when referencing it in generated code.
func (m *importManager) add(path, name string) string {
	if e, ok := m.byPath[path]; ok {
		return e.Alias
	}
	alias := name
	for i := 2; m.used[alias]; i++ {
		alias = fmt.Sprintf("%s%d", name, i)
	}
	e := &importEntry{Path: path, Alias: alias, Aliased: alias != name}
	m.byPath[path] = e
	m.used[alias] = true
	m.order = append(m.order, path)
	return alias
}

func (m *importManager) entries() []importEntry {
	out := make([]importEntry, 0, len(m.order))
	for _, p := range m.order {
		out = append(out, *m.byPath[p])
	}
	return out
}
