package commandsgen

import (
	"bytes"
	"fmt"
	"regexp"
	"sort"
	"strings"
)

// GenerateDocsFiles generates the MDX documentation files from parsed commands.
//
// subdirNames lists command names whose subcommands should each be written to
// their own file within a subdirectory instead of being combined into a single
// file. For example, passing "cloud" produces cloud/namespace.mdx, cloud/user.mdx,
// etc. rather than a single, unmanageably large cloud.mdx.
//
// Index/landing pages are intentionally not generated: on the docs site they are
// hand-maintained (custom ordering, front matter, embedded components), so
// generating them would overwrite that curated content.
func GenerateDocsFiles(commands Commands, subdirNames []string) (map[string][]byte, error) {
	optionSetMap := make(map[string]OptionSets)
	for i, optionSet := range commands.OptionSets {
		optionSetMap[optionSet.Name] = commands.OptionSets[i]
	}

	splitParents := make(map[string]bool)
	for _, name := range subdirNames {
		splitParents[name] = true
	}

	w := &docWriter{
		fileMap:        make(map[string]*bytes.Buffer),
		optionSetMap:   optionSetMap,
		allCommands:    commands.CommandList,
		globalFlagsMap: make(map[string]map[string]Option),
		splitParents:   splitParents,
	}

	// sorted ascending by full name of command (activity complete, batch list, etc)
	for _, cmd := range commands.CommandList {
		if err := cmd.writeDoc(w); err != nil {
			return nil, fmt.Errorf("failed writing docs for command %s: %w", cmd.FullName, err)
		}
	}

	// Write global flags section once at the end of each file
	w.writeGlobalFlagsSections()

	// Format and return
	var finalMap = make(map[string][]byte)
	for key, buf := range w.fileMap {
		finalMap[key] = buf.Bytes()
	}
	return finalMap, nil
}

type docWriter struct {
	allCommands    []Command
	fileMap        map[string]*bytes.Buffer
	optionSetMap   map[string]OptionSets
	optionsStack   [][]Option
	globalFlagsMap map[string]map[string]Option // fileName -> optionName -> Option
	splitParents   map[string]bool              // command names whose subcommands are split into a subdirectory
}

func (c *Command) writeDoc(w *docWriter) error {
	w.processOptions(c)

	depth := c.depth()

	// A split parent (e.g. "cloud") has no standalone file; its children are
	// each written into a subdirectory instead.
	if w.splitParents[c.FullName] {
		return nil
	}
	// If any ancestor is a split parent, route this command into that subdirectory.
	// FullName segments are separated by single spaces (never multiple), so
	// splitting on " " yields the exact command path.
	if depth >= 1 {
		parts := strings.Split(c.FullName, " ")
		for i := len(parts) - 1; i >= 1; i-- {
			ancestor := strings.Join(parts[:i], " ")
			if w.splitParents[ancestor] {
				c.writeSplitDoc(w, ancestor)
				return nil
			}
		}
	}

	if depth == 1 {
		w.writeCommand(c)
	} else if depth > 1 {
		w.writeSubcommand(c)
	}
	return nil
}

func (w *docWriter) writeCommand(c *Command) {
	fileName := c.fileName()
	w.fileMap[fileName] = &bytes.Buffer{}
	w.fileMap[fileName].WriteString("---\n")
	w.fileMap[fileName].WriteString("id: " + fileName + "\n")
	w.fileMap[fileName].WriteString("title: Temporal CLI " + fileName + " command reference\n")
	w.fileMap[fileName].WriteString("sidebar_label: " + fileName + "\n")
	w.fileMap[fileName].WriteString("description: " + c.Docs.DescriptionHeader + "\n")
	w.fileMap[fileName].WriteString("toc_max_heading_level: 4\n")

	w.fileMap[fileName].WriteString("keywords:\n")
	for _, keyword := range c.Docs.Keywords {
		w.fileMap[fileName].WriteString("  - " + keyword + "\n")
	}
	w.fileMap[fileName].WriteString("tags:\n")
	for _, tag := range c.Docs.Tags {
		w.fileMap[fileName].WriteString("  - " + tag + "\n")
	}
	w.fileMap[fileName].WriteString("---")
	w.fileMap[fileName].WriteString("\n\n")
	w.fileMap[fileName].WriteString(autoGeneratedNotice)
	// Add introductory paragraph
	w.fileMap[fileName].WriteString(fmt.Sprintf("This page provides a reference for the `temporal` CLI `%s` command. ", fileName))
	w.fileMap[fileName].WriteString("The flags applicable to each subcommand are presented in a table within the heading for the subcommand. ")
	w.fileMap[fileName].WriteString("Refer to [Global Flags](#global-flags) for flags that you can use with every subcommand.\n\n")
}

func (w *docWriter) writeSubcommand(c *Command) {
	fileName := c.fileName()
	prefix := strings.Repeat("#", c.depth())
	w.fileMap[fileName].WriteString(prefix + " " + c.leafName() + "\n\n")
	w.fileMap[fileName].WriteString(escapeMDXDescription(c.Description) + "\n\n")

	if w.isLeafCommand(c) {
		w.writeLeafOptions(fileName)
	}
}

// writeLeafOptions writes the option table (or the global-flags fallback message)
// for a leaf command, and records its inherited options for the file's Global
// Flags section. The command's own options are the top frame of the options
// stack; everything below it is inherited from parent commands.
//
// The reference to the "#global-flags" anchor is only emitted when there are
// inherited options, since that is what causes a Global Flags section (and thus
// the anchor) to be generated for the file. A command with no inherited options
// (e.g. a top-level command in a split subdirectory) would otherwise link to an
// anchor that never exists.
func (w *docWriter) writeLeafOptions(fileName string) {
	var options, globalOptions []Option
	for i, o := range w.optionsStack {
		if i == len(w.optionsStack)-1 {
			options = append(options, o...)
		} else {
			globalOptions = append(globalOptions, o...)
		}
	}

	sort.Slice(options, func(i, j int) bool {
		return options[i].Name < options[j].Name
	})

	buf := w.fileMap[fileName]
	hasGlobal := len(globalOptions) > 0
	switch {
	case len(options) > 0 && hasGlobal:
		buf.WriteString("Use the following options to change the behavior of this command. ")
		buf.WriteString("You can also use any of the [global flags](#global-flags) that apply to all subcommands.\n\n")
		w.writeOptionsTable(options, fileName)
	case len(options) > 0:
		buf.WriteString("Use the following options to change the behavior of this command.\n\n")
		w.writeOptionsTable(options, fileName)
	case hasGlobal:
		buf.WriteString("Use [global flags](#global-flags) to customize the connection to the Temporal Service for this command.\n\n")
	}

	w.collectGlobalFlags(fileName, globalOptions)
}

// writeSplitDoc routes a command that lives under a split parent to the right
// writer: direct children get their own file, deeper subcommands are appended
// as headings within their parent's file.
func (c *Command) writeSplitDoc(w *docWriter, splitRoot string) {
	splitDepth := len(strings.Split(splitRoot, " "))
	relativeDepth := len(strings.Split(c.FullName, " ")) - splitDepth

	switch {
	case relativeDepth == 1:
		w.writeSplitCommand(c, splitRoot)
	case relativeDepth > 1:
		w.writeSplitSubcommand(c, splitRoot)
	}
}

// splitFileName returns the file path for a command within a split parent.
// For example, with splitRoot "cloud" and command "cloud namespace", it returns
// "cloud/namespace". A multi-word split root is hyphenated into a single
// directory: splitRoot "one two" with command "one two three" returns
// "one-two/three" (not "one/two/three").
func splitFileName(c *Command, splitRoot string) string {
	splitParts := strings.Split(splitRoot, " ")
	cmdParts := strings.Split(c.FullName, " ")
	if len(cmdParts) <= len(splitParts) {
		return ""
	}
	return strings.Join(splitParts, "-") + "/" + cmdParts[len(splitParts)]
}

func (w *docWriter) writeSplitCommand(c *Command, splitRoot string) {
	fileName := splitFileName(c, splitRoot)
	splitParts := strings.Split(splitRoot, " ")
	cmdParts := strings.Split(c.FullName, " ")
	leafName := cmdParts[len(splitParts)]

	buf := &bytes.Buffer{}
	w.fileMap[fileName] = buf
	buf.WriteString("---\n")
	buf.WriteString("id: " + leafName + "\n")
	buf.WriteString("title: Temporal CLI " + c.FullName + " command reference\n")
	buf.WriteString("sidebar_label: " + leafName + "\n")
	buf.WriteString("description: " + c.Docs.DescriptionHeader + "\n")
	buf.WriteString("toc_max_heading_level: 4\n")
	buf.WriteString("keywords:\n")
	for _, keyword := range c.Docs.Keywords {
		buf.WriteString("  - " + keyword + "\n")
	}
	buf.WriteString("tags:\n")
	for _, tag := range c.Docs.Tags {
		buf.WriteString("  - " + tag + "\n")
	}
	buf.WriteString("---")
	buf.WriteString("\n\n")
	buf.WriteString(autoGeneratedNotice)

	buf.WriteString(escapeMDXDescription(c.Description) + "\n\n")

	if w.isLeafCommand(c) {
		w.writeLeafOptions(fileName)
	} else {
		buf.WriteString(fmt.Sprintf("This page provides a reference for the `temporal %s` commands. ", c.FullName))
		buf.WriteString("The flags applicable to each subcommand are presented in a table within the heading for the subcommand. ")
		buf.WriteString("Refer to [Global Flags](#global-flags) for flags that you can use with every subcommand.\n\n")
	}
}

func (w *docWriter) writeSplitSubcommand(c *Command, splitRoot string) {
	fileName := splitFileName(c, splitRoot)
	splitParts := strings.Split(splitRoot, " ")
	cmdParts := strings.Split(c.FullName, " ")
	relativeDepth := len(cmdParts) - len(splitParts)
	prefix := strings.Repeat("#", relativeDepth)
	// Use the path relative to the split root (e.g. "ha update", "cert-ca create")
	// rather than just the final segment. Within one aggregated file this keeps
	// each heading's generated anchor unique and stable, which other docs link to
	// (e.g. /cloud/high-availability/enable -> cloud/namespace#ha-update).
	leafName := strings.Join(cmdParts[len(splitParts)+1:], " ")

	buf := w.fileMap[fileName]
	buf.WriteString(prefix + " " + leafName + "\n\n")
	buf.WriteString(escapeMDXDescription(c.Description) + "\n\n")

	if w.isLeafCommand(c) {
		w.writeLeafOptions(fileName)
	}
}

func (w *docWriter) writeOptionsTable(options []Option, fileName string) {
	if len(options) == 0 {
		return
	}

	buf := w.fileMap[fileName]

	// Command-specific flags: 3 columns (no Default)
	buf.WriteString("| Flag | Required | Description |\n")
	buf.WriteString("|------|----------|-------------|\n")

	for _, o := range options {
		w.writeOptionRow(buf, o, false)
	}
	buf.WriteString("\n")
}

func (w *docWriter) writeOptionRow(buf *bytes.Buffer, o Option, includeDefault bool) {
	// Flag name column
	flagName := fmt.Sprintf("`--%s`", o.Name)
	if len(o.Short) > 0 {
		flagName += fmt.Sprintf(", `-%s`", o.Short)
	}

	// Required column
	required := "No"
	if o.Required {
		required = "Yes"
	}

	// Description column - starts with data type
	optionType := o.Type
	if o.DisplayType != "" {
		optionType = o.DisplayType
	}
	description := fmt.Sprintf("**%s** %s", optionType, encodeJSONExample(o.Description))
	if len(o.EnumValues) > 0 {
		description += fmt.Sprintf(" Accepted values: %s.", strings.Join(o.EnumValues, ", "))
	}
	if o.Experimental {
		description += " _(Experimental)_"
	}
	// Escape pipes in description for table compatibility
	description = strings.ReplaceAll(description, "|", "\\|")

	if includeDefault {
		// Default column
		defaultVal := ""
		if len(o.Default) > 0 {
			defaultVal = fmt.Sprintf("`%s`", o.Default)
		}
		buf.WriteString(fmt.Sprintf("| %s | %s | %s | %s |\n", flagName, required, description, defaultVal))
	} else {
		buf.WriteString(fmt.Sprintf("| %s | %s | %s |\n", flagName, required, description))
	}
}

func (w *docWriter) collectGlobalFlags(fileName string, options []Option) {
	if w.globalFlagsMap[fileName] == nil {
		w.globalFlagsMap[fileName] = make(map[string]Option)
	}
	for _, o := range options {
		// Only add if not already present (deduplication)
		if _, exists := w.globalFlagsMap[fileName][o.Name]; !exists {
			w.globalFlagsMap[fileName][o.Name] = o
		}
	}
}

func (w *docWriter) writeGlobalFlagsSections() {
	for fileName, optionsMap := range w.globalFlagsMap {
		if len(optionsMap) == 0 {
			continue
		}

		// Convert map to slice and sort
		options := make([]Option, 0, len(optionsMap))
		for _, o := range optionsMap {
			options = append(options, o)
		}
		sort.Slice(options, func(i, j int) bool {
			return options[i].Name < options[j].Name
		})

		buf := w.fileMap[fileName]
		buf.WriteString("## Global Flags\n\n")
		buf.WriteString("The following options can be used with any command.\n\n")
		// Global flags: 4 columns (with Default)
		buf.WriteString("| Flag | Required | Description | Default |\n")
		buf.WriteString("|------|----------|-------------|--------|\n")

		for _, o := range options {
			w.writeOptionRow(buf, o, true)
		}
		buf.WriteString("\n")
	}
}

func (w *docWriter) processOptions(c *Command) {
	// Pop options from stack if we are moving up a level
	if len(w.optionsStack) >= len(strings.Split(c.FullName, " ")) {
		w.optionsStack = w.optionsStack[:len(w.optionsStack)-1]
	}
	var options []Option
	options = append(options, c.Options...)

	// Maintain stack of options available from parent commands
	for _, set := range c.OptionSets {
		optionSet, ok := w.optionSetMap[set]
		if !ok {
			panic(fmt.Sprintf("invalid option set %v used", set))
		}
		optionSetOptions := optionSet.Options
		options = append(options, optionSetOptions...)
	}

	w.optionsStack = append(w.optionsStack, options)
}

func (w *docWriter) isLeafCommand(c *Command) bool {
	for _, maybeSubCmd := range w.allCommands {
		if maybeSubCmd.isSubCommand(c) {
			return false
		}
	}
	return true
}

const autoGeneratedNotice = "{/* NOTE: This is an auto-generated file. Any edit to this file will be overwritten.\n" +
	"This file is generated from the CLI command definitions via cmd/gen-docs. */}\n\n"

// jsonInSingleQuotes matches a single-quoted string containing curly braces,
// e.g. 'YourKey={"a":"b"}' or '{"a":"b"}'. MDX interprets the braces as a JSX
// expression, so such examples must be wrapped in backticks (option table cells)
// or backslash-escaped (description body text).
var jsonInSingleQuotes = regexp.MustCompile(`'[^']*\{[^']*\}[^']*'`)

// angleBracketPlaceholder matches lowercase angle-bracket placeholders such as
// <base64-encoded-cert>, <key>, or <requests_per_second:float>. Restricting the
// match to lowercase, multi-character names avoids escaping legitimate inline
// HTML that authors may intentionally include.
var angleBracketPlaceholder = regexp.MustCompile(`<([a-z][a-z0-9_:.-]+)>`)

// headingID matches a Markdown heading line ending with a custom ID, e.g.
// "### Some heading {#custom-id}". The Docusaurus MDX parser (3.10+) treats the
// bare {#custom-id} as a JSX expression and fails to compile it.
var headingID = regexp.MustCompile(`^(#{1,6}\s+.+?)\s+\{#([\w-]+)\}\s*$`)

// encodeJSONExample wraps single-quoted JSON examples in backticks so MDX renders
// them as inline code rather than parsing the curly braces as a JSX expression.
// This handles option description table cells; escapeMDXDescription handles the
// same class of issue for command description body text.
func encodeJSONExample(v string) string {
	return jsonInSingleQuotes.ReplaceAllString(v, "`$0`")
}

// escapeMDXDescription escapes patterns in a command description that are valid
// CommonMark but break MDX (JSX) compilation under Docusaurus 3.10+:
//
//   - bare angle-bracket placeholders like <base64-encoded-cert>, which MDX
//     parses as an unclosed JSX/HTML tag;
//   - curly braces in single-quoted JSON examples like '{"a":"b"}', which MDX
//     parses as a JSX expression; and
//   - custom heading IDs like "## Heading {#id}", where MDX parses the {#id} as
//     a JSX expression and fails on the '#'. These are converted to Docusaurus's
//     MDX-compatible {/* #id */} comment form, which preserves the custom anchor.
//
// Content inside fenced code blocks (```) and inline code spans (backticks) is
// left untouched, since MDX does not interpret those as JSX. Fence markers are
// assumed to be on their own line (the standard CommonMark form the command
// descriptions use): a ``` opening or closing a block must start the line.
func escapeMDXDescription(desc string) string {
	lines := strings.Split(desc, "\n")
	inCodeBlock := false
	for i, line := range lines {
		if strings.HasPrefix(strings.TrimSpace(line), "```") {
			inCodeBlock = !inCodeBlock
			continue
		}
		if inCodeBlock {
			continue
		}

		line = headingID.ReplaceAllString(line, "$1 {/* #$2 */}")

		// Escape only outside inline code spans. Splitting on backticks yields
		// alternating outside/inside segments (assuming balanced backticks).
		segments := strings.Split(line, "`")
		for j := range segments {
			if j%2 != 0 {
				continue // inside an inline code span
			}
			segments[j] = angleBracketPlaceholder.ReplaceAllString(segments[j], `\<$1\>`)
			segments[j] = jsonInSingleQuotes.ReplaceAllStringFunc(segments[j], func(m string) string {
				return strings.NewReplacer("{", `\{`, "}", `\}`).Replace(m)
			})
		}
		lines[i] = strings.Join(segments, "`")
	}
	return strings.Join(lines, "\n")
}
