package commandsgen

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
)

// envVarEntry is one documented shell environment variable.
type envVarEntry struct {
	EnvVar      string
	Flag        string
	Description string
}

// legacyPresetEnvVars configure the `temporal env` preset system rather than the
// TOML config file. They get their own section so they are not read as peers of
// the profile-based settings, which use a different file in a different format.
var legacyPresetEnvVars = map[string]bool{
	"TEMPORAL_ENV":      true,
	"TEMPORAL_ENV_FILE": true,
}

// GenerateEnvVarDocsFile builds an MDX index of shell environment variables
// derived from options with implied-env, plus a few special cases that are not
// simple 1:1 flag mappings.
//
// Returns nil when there are no implied-env options (so callers can skip writing
// a file, e.g. during cloud-cli -subdir generation that would otherwise overwrite
// the main CLI env-var page).
func GenerateEnvVarDocsFile(commands Commands) []byte {
	entries := collectImpliedEnvVars(commands)
	if len(entries) == 0 {
		return nil
	}

	// Legacy `temporal env` variables are split out of the main table so readers
	// do not mistake them for the current profile-based settings.
	var current, legacyPreset []envVarEntry
	for _, e := range entries {
		if legacyPresetEnvVars[e.EnvVar] {
			legacyPreset = append(legacyPreset, e)
		} else {
			current = append(current, e)
		}
	}

	var buf bytes.Buffer
	buf.WriteString("---\n")
	buf.WriteString("id: environment-variables\n")
	buf.WriteString("title: Temporal CLI environment variables reference\n")
	buf.WriteString("sidebar_label: environment variables\n")
	buf.WriteString("description: Shell environment variables that configure Temporal CLI flags.\n")
	buf.WriteString("toc_max_heading_level: 4\n")
	buf.WriteString("keywords:\n")
	buf.WriteString("  - temporal cli\n")
	buf.WriteString("  - environment variables\n")
	buf.WriteString("  - configuration\n")
	buf.WriteString("tags:\n")
	buf.WriteString("  - Temporal CLI\n")
	buf.WriteString("---\n\n")
	buf.WriteString(autoGeneratedNotice)

	buf.WriteString("This page lists shell environment variables that configure the Temporal CLI.\n\n")
	buf.WriteString("Setting a shell environment variable is not the same as storing a preset with\n")
	buf.WriteString("[`temporal env`](/cli/command-reference/env). A shell variable configures the CLI process,\n")
	buf.WriteString("while `temporal env` writes named key-value presets to a file. Two shell variables control\n")
	buf.WriteString("which preset the CLI reads, and they are listed under\n")
	buf.WriteString("[Legacy `temporal env` variables](#legacy-temporal-env-variables).\n\n")
	buf.WriteString("When both a flag and its environment variable are set, the flag takes precedence.\n\n")

	writeEnvVarTable(&buf, current)

	buf.WriteString("## Special cases\n\n")
	buf.WriteString("### `TEMPORAL_GRPC_META_*`\n\n")
	buf.WriteString("HTTP headers for requests can be set with `--grpc-meta KEY=VALUE` (repeatable), or via\n")
	buf.WriteString("environment variables named `TEMPORAL_GRPC_META_[name]`, where `[name]` is the header name.\n\n")
	buf.WriteString("### Legacy TLS variables\n\n")
	buf.WriteString("For compatibility, the following legacy TLS environment variables still work and override\n")
	buf.WriteString("values loaded from the config file or the preferred TLS variables above:\n\n")
	buf.WriteString("| Legacy variable | Preferred equivalent |\n")
	buf.WriteString("|-----------------|----------------------|\n")
	buf.WriteString("| `TEMPORAL_TLS_CERT` | `TEMPORAL_TLS_CLIENT_CERT_PATH` |\n")
	buf.WriteString("| `TEMPORAL_TLS_CERT_DATA` | `TEMPORAL_TLS_CLIENT_CERT_DATA` |\n")
	buf.WriteString("| `TEMPORAL_TLS_KEY` | `TEMPORAL_TLS_CLIENT_KEY_PATH` |\n")
	buf.WriteString("| `TEMPORAL_TLS_KEY_DATA` | `TEMPORAL_TLS_CLIENT_KEY_DATA` |\n")
	buf.WriteString("| `TEMPORAL_TLS_CA` | `TEMPORAL_TLS_SERVER_CA_CERT_PATH` |\n")
	buf.WriteString("| `TEMPORAL_TLS_CA_DATA` | `TEMPORAL_TLS_SERVER_CA_CERT_DATA` |\n")
	buf.WriteString("\n")

	if len(legacyPreset) > 0 {
		buf.WriteString("### Legacy `temporal env` variables\n\n")
		buf.WriteString("These variables point the CLI at the `temporal env` preset system, which stores named\n")
		buf.WriteString("key-value presets in `temporal.yaml`. Profiles in the TOML config file supersede that\n")
		buf.WriteString("system: use `TEMPORAL_PROFILE` to select a profile and `TEMPORAL_CONFIG_FILE` to point at\n")
		buf.WriteString("a `temporal.toml` file. The variables below still work.\n\n")
		writeEnvVarTable(&buf, legacyPreset)
	}

	return buf.Bytes()
}

// writeEnvVarTable renders entries as an MDX table of variable, flag, and description.
func writeEnvVarTable(buf *bytes.Buffer, entries []envVarEntry) {
	buf.WriteString("| Environment variable | Flag | Description |\n")
	buf.WriteString("|----------------------|------|-------------|\n")
	for _, e := range entries {
		desc := encodeJSONExample(e.Description)
		desc = strings.ReplaceAll(desc, "|", "\\|")
		buf.WriteString(fmt.Sprintf("| `%s` | `--%s` | %s |\n", e.EnvVar, e.Flag, desc))
	}
	buf.WriteString("\n")
}

func collectImpliedEnvVars(commands Commands) []envVarEntry {
	byEnv := make(map[string]envVarEntry)

	add := func(o Option) {
		if o.ImpliedEnv == "" || o.Hidden {
			return
		}
		// First definition wins; later duplicates (same env across option sets) are ignored.
		if _, exists := byEnv[o.ImpliedEnv]; exists {
			return
		}
		byEnv[o.ImpliedEnv] = envVarEntry{
			EnvVar:      o.ImpliedEnv,
			Flag:        o.Name,
			Description: o.Description,
		}
	}

	for _, set := range commands.OptionSets {
		if set.ExternalPackage != "" {
			continue
		}
		for _, o := range set.Options {
			add(o)
		}
	}
	for _, cmd := range commands.CommandList {
		for _, o := range cmd.Options {
			add(o)
		}
	}

	entries := make([]envVarEntry, 0, len(byEnv))
	for _, e := range byEnv {
		entries = append(entries, e)
	}
	sort.Slice(entries, func(i, j int) bool {
		return entries[i].EnvVar < entries[j].EnvVar
	})
	return entries
}
