// Code generated by gen-system-nexus. DO NOT EDIT.

package temporalcli

import (
	"go.temporal.io/api/workflowservice/v1"
	"go.temporal.io/api/workflowservice/v1/workflowservicenexus"
	"google.golang.org/protobuf/proto"
)

// systemNexusOps is the generated registry of known system Nexus operations on
// the __temporal_system endpoint. Regenerate with 'make gen' after bumping the
// go.temporal.io/api dependency.
var systemNexusOps = map[systemNexusOpKey]systemNexusOpTypes{
	{
		Endpoint:  temporalSystemNexusEndpoint,
		Operation: workflowservicenexus.TemporalAPIWorkflowserviceV1WorkflowService.SignalWithStartWorkflowExecution.Name(),
	}: {
		NewRequest:  func() proto.Message { return &workflowservice.SignalWithStartWorkflowExecutionRequest{} },
		NewResponse: func() proto.Message { return &workflowservice.SignalWithStartWorkflowExecutionResponse{} },
	},
}
