package temporalcli

import (
	"errors"
	"fmt"
	"io"
	"runtime"
	"sort"
	"strings"
	"unicode"
)

const defaultFailureExitStatus = 1

// Result describes the terminal outcome without exiting the process. The
// original command error remains separate from any failure writing stderr.
type Result struct {
	CommandErr      error
	PresentationErr error
	ExitStatus      int
}

type checkOutcome int

const (
	checkSucceeded checkOutcome = iota
	checkFailed
	checkInconclusive
	checkSkipped
)

type safeField struct {
	Label string
	Value string
}

type errorCheck struct {
	Outcome checkOutcome
	Message string
}

type displayInvocation struct {
	Command []string
	Args    []string
}

type displayAction struct {
	Label       string
	Invocations []displayInvocation
}

type errorReport struct {
	Summary      string
	Context      []safeField
	CheckHeading string
	Checks       []errorCheck
	Action       *displayAction
	Usage        string
}

type renderOptions struct {
	Color bool
	Shell displayShell
}

type displayShell int

const (
	displayShellPOSIX displayShell = iota
	displayShellPowerShell
)

type terminalOptions struct {
	Stderr       io.Writer
	Color        bool
	KnownSecrets []string
	Usage        string
	DisplayErr   error
}

func handleTerminalError(commandErr error, options terminalOptions) Result {
	result := Result{CommandErr: commandErr, ExitStatus: defaultFailureExitStatus}
	displayErr := options.DisplayErr
	if displayErr == nil {
		displayErr = commandErr
	}
	report := normalizeError(displayErr)
	report.Usage = options.Usage
	report = redactReport(report, options.KnownSecrets)
	shell := displayShellPOSIX
	if runtime.GOOS == "windows" {
		shell = displayShellPowerShell
	}
	rendered := renderErrorText(report, renderOptions{Color: options.Color, Shell: shell})
	n, err := options.Stderr.Write(rendered)
	if err == nil && n != len(rendered) {
		err = io.ErrShortWrite
	}
	result.PresentationErr = err
	return result
}

func normalizeError(err error) errorReport {
	var connectionErr *connectError
	if errors.As(err, &connectionErr) {
		return connectionErrorReport(connectionErr)
	}
	var activityErr *activityNotFoundError
	if errors.As(err, &activityErr) {
		return activityNotFoundErrorReport(activityErr)
	}
	if err == nil || err.Error() == "" {
		return errorReport{Summary: "unknown error"}
	}
	return errorReport{Summary: err.Error()}
}

// activityNotFoundErrorReport is the concrete terminal-owned adapter for a
// missing standalone Activity. The typed error retains identity and cause;
// this adapter preserves the deliberately conservative visible message.
func activityNotFoundErrorReport(_ *activityNotFoundError) errorReport {
	return errorReport{Summary: "standalone Activity not found"}
}

// connectionErrorReport is the concrete terminal-owned adapter for connection
// failures. connectError carries facts and never owns presentation layout.
func connectionErrorReport(err *connectError) errorReport {
	report := errorReport{Summary: err.Error(), Action: suggestAction(&err.diagnosis, err.meta)}
	if err.meta.Namespace != "" {
		report.Context = append(report.Context, safeField{Label: "Namespace", Value: err.meta.Namespace})
	}
	if err.meta.Address != "" {
		report.Context = append(report.Context, safeField{Label: "TLS", Value: fmt.Sprintf("%t", err.meta.TLSConfigured)})
	}
	if len(err.diagnosis.Stages) > 0 {
		report.CheckHeading = "Connection checks"
		if err.meta.Address != "" {
			report.CheckHeading += " for " + err.meta.Address
		}
	}
	for _, stage := range err.diagnosis.Stages {
		outcome := checkInconclusive
		switch stage.Status {
		case diagOK:
			outcome = checkSucceeded
		case diagFail:
			outcome = checkFailed
		case diagSkipped:
			outcome = checkSkipped
		}
		report.Checks = append(report.Checks, errorCheck{Outcome: outcome, Message: stage.Label})
	}
	return report
}

func redactReport(report errorReport, secrets []string) errorReport {
	// This is defense in depth for exact values already known to the runtime,
	// not a claim that arbitrary legacy error prose is generically sanitized.
	// Structured adapters remain responsible for admitting only safe fields.
	report = cloneErrorReport(report)
	orderedSecrets := append([]string(nil), secrets...)
	sort.Slice(orderedSecrets, func(i, j int) bool {
		if len(orderedSecrets[i]) == len(orderedSecrets[j]) {
			return orderedSecrets[i] < orderedSecrets[j]
		}
		return len(orderedSecrets[i]) > len(orderedSecrets[j])
	})
	redact := func(value string) string {
		for _, secret := range orderedSecrets {
			if secret != "" {
				value = strings.ReplaceAll(value, secret, "[REDACTED]")
			}
		}
		return escapeTerminalControls(value)
	}
	report.Summary = redact(report.Summary)
	// Usage is generated by Cobra and intentionally contains formatting
	// newlines. It receives exact-value redaction but not control escaping.
	for _, secret := range orderedSecrets {
		if secret != "" {
			report.Usage = strings.ReplaceAll(report.Usage, secret, "[REDACTED]")
		}
	}
	for i := range report.Context {
		report.Context[i].Label = redact(report.Context[i].Label)
		report.Context[i].Value = redact(report.Context[i].Value)
	}
	report.CheckHeading = redact(report.CheckHeading)
	for i := range report.Checks {
		report.Checks[i].Message = redact(report.Checks[i].Message)
	}
	if report.Action != nil {
		report.Action.Label = redact(report.Action.Label)
		for invocationIndex := range report.Action.Invocations {
			invocation := &report.Action.Invocations[invocationIndex]
			for i := range invocation.Command {
				invocation.Command[i] = redact(invocation.Command[i])
			}
			for i := range invocation.Args {
				invocation.Args[i] = redact(invocation.Args[i])
			}
		}
	}
	return report
}

func cloneErrorReport(report errorReport) errorReport {
	clone := report
	clone.Context = append([]safeField(nil), report.Context...)
	clone.Checks = append([]errorCheck(nil), report.Checks...)
	if report.Action == nil {
		return clone
	}
	action := *report.Action
	action.Invocations = append([]displayInvocation(nil), report.Action.Invocations...)
	for i := range action.Invocations {
		action.Invocations[i].Command = append([]string(nil), action.Invocations[i].Command...)
		action.Invocations[i].Args = append([]string(nil), action.Invocations[i].Args...)
	}
	clone.Action = &action
	return clone
}

func escapeTerminalControls(value string) string {
	var b strings.Builder
	for _, r := range value {
		if !unicode.IsControl(r) {
			b.WriteRune(r)
			continue
		}
		switch r {
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		default:
			fmt.Fprintf(&b, `\u{%x}`, r)
		}
	}
	return b.String()
}

// renderErrorText is total over errorReport and performs no I/O or global
// color lookup. Reports are redacted before reaching this function.
func renderErrorText(report errorReport, options renderOptions) []byte {
	if report.Summary == "" {
		report.Summary = "unknown error"
	}
	var b strings.Builder
	b.WriteString("Error: ")
	b.WriteString(report.Summary)
	b.WriteByte('\n')
	for _, field := range report.Context {
		fmt.Fprintf(&b, "  %s: %s\n", field.Label, field.Value)
	}
	if len(report.Checks) > 0 {
		heading := report.CheckHeading
		if heading == "" {
			heading = "Connecting"
		}
		fmt.Fprintf(&b, "\n  %s\n", heading)
		for _, check := range report.Checks {
			symbol := "✓"
			colorCode := "32"
			if check.Outcome == checkFailed {
				symbol = "✗"
				colorCode = "31"
			} else if check.Outcome == checkInconclusive {
				symbol = "?"
				colorCode = "33"
			} else if check.Outcome == checkSkipped {
				symbol = "-"
				colorCode = "33"
			}
			if options.Color {
				symbol = "\x1b[" + colorCode + "m" + symbol + "\x1b[0m"
			}
			fmt.Fprintf(&b, "    %s %s\n", symbol, check.Message)
		}
	}
	if report.Action != nil {
		b.WriteByte('\n')
		if report.Action.Label != "" {
			b.WriteString(indentLines(report.Action.Label, "  "))
			b.WriteByte('\n')
		}
		for _, invocation := range report.Action.Invocations {
			rendered, ok := renderInvocation(invocation, options.Shell)
			if !ok {
				continue
			}
			b.WriteByte('\n')
			b.WriteString("    ")
			b.WriteString(rendered)
			b.WriteByte('\n')
		}
	}
	if report.Usage != "" {
		b.WriteByte('\n')
		b.WriteString(strings.TrimLeft(report.Usage, "\n"))
		if !strings.HasSuffix(report.Usage, "\n") {
			b.WriteByte('\n')
		}
	}
	return []byte(b.String())
}

func renderInvocation(invocation displayInvocation, shell displayShell) (string, bool) {
	parts := append([]string(nil), invocation.Command...)
	parts = append(parts, invocation.Args...)
	if len(parts) == 0 {
		return "", false
	}
	for i := range parts {
		parts[i] = escapeTerminalControls(parts[i])
		if shell == displayShellPowerShell {
			parts[i] = quotePowerShell(parts[i])
		} else {
			parts[i] = quotePOSIX(parts[i])
		}
	}
	rendered := strings.Join(parts, " ")
	if shell == displayShellPowerShell {
		rendered = "& " + rendered
	}
	return rendered, true
}

func quotePOSIX(value string) string {
	if value != "" && strings.IndexFunc(value, func(r rune) bool {
		return !(unicode.IsLetter(r) || unicode.IsDigit(r) || strings.ContainsRune("_@%+=:,./-", r))
	}) < 0 {
		return value
	}
	return "'" + strings.ReplaceAll(value, "'", "'\"'\"'") + "'"
}

func quotePowerShell(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "''") + "'"
}

func indentLines(s, indent string) string {
	lines := strings.Split(s, "\n")
	for i, line := range lines {
		if line != "" {
			lines[i] = indent + line
		}
	}
	return strings.Join(lines, "\n")
}
