history.enableCHASMSchedulerCreation:
  - value: true
    constraints:
      namespace: fx-test

history.chasmSchedulerCreationRolloutPercent:
  - value: 100
    constraints:
      namespace: fx-test

history.enableCHASMSchedulerRouting:
  - value: true
    constraints:
      namespace: fx-test
